services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rawgDatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  seeder:
    container_name: seeder
    build:
      context: ./seeder
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      MYSQL_URL: mysql://root:rootpassword@mysql:3306/rawgDatabase

  rawg-server:
    container_name: rawg-server
    build:
      context: ./rawg-server
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:rootpassword@mysql:3306/rawgDatabase
    ports:
      - "5000:5000"


volumes:
  mysql_data: